const DEPRECATED_UI_COMPONENTS = [
  'Accordion',
  'AccordionItem',
  'ActionIcon',
  'Alert',
  'AutoComplete',
  'Avatar',
  'Button',
  'Checkbox',
  'CheckboxGroup',
  'Collapse',
  'DraggablePanel',
  'DraggablePanelBody',
  'DraggablePanelContainer',
  'DraggablePanelFooter',
  'DraggablePanelHeader',
  'Drawer',
  'Dropdown',
  'FormSubmitFooter',
  'FormTitle',
  'InputOPT',
  'Modal',
  'Radio',
  'RadioGroup',
  'Segmented',
  'Select',
  'Skeleton',
  'SkeletonAvatar',
  'SkeletonBlock',
  'SkeletonButton',
  'SkeletonParagraph',
  'SkeletonTags',
  'SkeletonTitle',
  'Slider',
  'SliderWithInput',
  'Switch',
  'Tabs',
  'Tag',
  'Text',
  'Tree',
];

const DEPRECATED_ANTD_ONLY = [
  'Badge',
  'Empty',
  'Pagination',
  'Popover',
  'Progress',
  'Result',
  'Spin',
  'Tooltip',
  'Upload',
];

const DEPRECATED_ANTD_COMPONENT_PATHS = [
  'antd/es/alert',
  'antd/es/alert/*',
  'antd/es/auto-complete',
  'antd/es/auto-complete/*',
  'antd/es/badge',
  'antd/es/badge/*',
  'antd/es/checkbox',
  'antd/es/checkbox/*',
  'antd/es/collapse',
  'antd/es/collapse/*',
  'antd/es/dropdown',
  'antd/es/dropdown/*',
  'antd/es/empty',
  'antd/es/empty/*',
  'antd/es/message',
  'antd/es/message/*',
  'antd/es/notification',
  'antd/es/notification/*',
  'antd/es/pagination',
  'antd/es/pagination/*',
  'antd/es/popover',
  'antd/es/popover/*',
  'antd/es/progress',
  'antd/es/progress/*',
  'antd/es/radio',
  'antd/es/radio/*',
  'antd/es/result',
  'antd/es/result/*',
  'antd/es/skeleton',
  'antd/es/skeleton/*',
  'antd/es/slider',
  'antd/es/slider/*',
  'antd/es/spin',
  'antd/es/spin/*',
  'antd/es/switch',
  'antd/es/switch/*',
  'antd/es/tooltip',
  'antd/es/tooltip/*',
  'antd/es/tree',
  'antd/es/tree/*',
  'antd/es/upload',
  'antd/es/upload/*',
  'antd/lib/alert',
  'antd/lib/alert/*',
  'antd/lib/auto-complete',
  'antd/lib/auto-complete/*',
  'antd/lib/badge',
  'antd/lib/badge/*',
  'antd/lib/checkbox',
  'antd/lib/checkbox/*',
  'antd/lib/collapse',
  'antd/lib/collapse/*',
  'antd/lib/dropdown',
  'antd/lib/dropdown/*',
  'antd/lib/empty',
  'antd/lib/empty/*',
  'antd/lib/message',
  'antd/lib/message/*',
  'antd/lib/notification',
  'antd/lib/notification/*',
  'antd/lib/pagination',
  'antd/lib/pagination/*',
  'antd/lib/popover',
  'antd/lib/popover/*',
  'antd/lib/progress',
  'antd/lib/progress/*',
  'antd/lib/radio',
  'antd/lib/radio/*',
  'antd/lib/result',
  'antd/lib/result/*',
  'antd/lib/skeleton',
  'antd/lib/skeleton/*',
  'antd/lib/slider',
  'antd/lib/slider/*',
  'antd/lib/spin',
  'antd/lib/spin/*',
  'antd/lib/switch',
  'antd/lib/switch/*',
  'antd/lib/tooltip',
  'antd/lib/tooltip/*',
  'antd/lib/tree',
  'antd/lib/tree/*',
  'antd/lib/upload',
  'antd/lib/upload/*',
];

export const restrictedImports = {
  rules: {
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            importNames: DEPRECATED_UI_COMPONENTS,
            message:
              'The antd-based wrapper is deprecated. Import from "@lobehub/ui/base-ui" instead.',
            name: '@lobehub/ui',
          },
          {
            importNames: ['createStyles'],
            message:
              '`createStyles` is banned in this project. Use `createStaticStyles` from "antd-style" instead.',
            name: 'antd-style',
          },
          {
            importNames: [...DEPRECATED_UI_COMPONENTS, ...DEPRECATED_ANTD_ONLY],
            message: 'Direct antd import is deprecated. Import from "@lobehub/ui/base-ui" instead.',
            name: 'antd',
          },
          {
            importNames: ['message', 'notification'],
            message: 'antd feedback APIs are deprecated. Use `toast` from "@lobehub/ui/base-ui".',
            name: 'antd',
          },
        ],
        patterns: [
          {
            group: DEPRECATED_ANTD_COMPONENT_PATHS,
            message:
              'Direct antd component import is deprecated. Import from "@lobehub/ui/base-ui" instead.',
          },
        ],
      },
    ],
  },
};

export default [restrictedImports];
