export const enum KeyMap {
  Alt = 'alt',
  Backspace = 'backspace',
  Ctrl = 'ctrl',
  Down = 'down',
  Enter = 'enter',
  Left = 'left',
  LeftClick = 'left-click',
  LeftDoubleClick = 'left-double-click',
  Meta = 'meta',
  MiddleClick = 'middle-click',
  Mod = 'mod',
  Right = 'right',
  RightClick = 'right-click',
  RightDoubleClick = 'right-double-click',
  Shift = 'shift',
  Space = 'space',
  Tab = 'tab',
  Up = 'up',
}
